### ISSUE TITLE
Server error mollie_account_sync

### ISSUE THREAD

**Issue by mealhero** [mollie/mollie-odoo#115]
Hello, when trying to sync settlements using the latest version of mollie_account_sync on Odoo 12, I get this error:

This wasn't the case before i updated the module. Any help?

`Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo_12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo_12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo_12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo_12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo_12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo_12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo_12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo_12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo_12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo_12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo_12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo_12/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo_12/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo_12/custom_module_demo/mollie_account_sync/wizard/mollie_init.py", line 64, in sync_settlement
    journal._process_settlements(settlements_data)
  File "/home/odoo_12/custom_module_demo/mollie_account_sync/models/account_journal.py", line 120, in _process_settlements
    self._create_bank_statements(payment_data, refund_data, captures_data, chargeback_data, settlement)
  File "/home/odoo_12/custom_module_demo/mollie_account_sync/models/account_journal.py", line 139, in _create_bank_statements
    'name': self._generate_payment_ref(payment['metadata']) or payment['description'],
  File "/home/odoo_12/custom_module_demo/mollie_account_sync/models/account_journal.py", line 434, in _generate_payment_ref
    if metadata.get('customer'):
AttributeError: 'str' object has no attribute 'get'`

**Comment by odoo-mvds** [comment]
Hello,

Can you tell us from where payments are coming? Are you using the payment acquirer of odoo? Or is your DB linked with some external webshop like magento or shopify?

It seems the issue is coming from there somewhere.

br,
