### ISSUE TITLE
Migration to Odoo 12.0

### ISSUE THREAD

**Issue by mgielissen** [mollie/mollie-odoo#13]
Same question as last year :)

**Comment by ploegvde** [comment]
One of our customers is also interested. Any plans?

**Comment by Yenthe666** [comment]
@Smitsel hi, could you please give us an update about the plans for V12? We now have two customers who want to use it. 😉

**Comment by gclauwae** [comment]
@Yenthe666 @Smitsel @ploegvde @mgielissen Hello, v12 now available without Refunds, we are working on that for a later version.
Enjoy Odoo + Mollie payments.
Gunther

**Comment by ipsecurity** [comment]
Hi, Thanks for version 12.0 module. we get an error when we try to install on version 12. 

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3821, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo/odoo/models.py", line 3735, in _load_records_create
    return self.create(values)
  File "<decorator-gen-313>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/addons/payment_transfer/models/payment.py", line 60, in create
    return super(TransferPaymentAcquirer, self).create(values)
  File "<decorator-gen-220>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/odoo/addons/payment/models/payment_acquirer.py", line 282, in create
    return super(PaymentAcquirer, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/odoo/models.py", line 3516, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/odoo/models.py", line 3602, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/opt/odoo/odoo/odoo/fields.py", line 1934, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1946, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for payment.acquirer.provider: 'mollie'

**Comment by ipsecurity** [comment]
Hi, Thanks for v12 module. We get an error when we try to install:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3821, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo/odoo/models.py", line 3735, in _load_records_create
    return self.create(values)
  File "<decorator-gen-313>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/odoo/addons/payment_transfer/models/payment.py", line 60, in create
    return super(TransferPaymentAcquirer, self).create(values)
  File "<decorator-gen-220>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/odoo/addons/payment/models/payment_acquirer.py", line 282, in create
    return super(PaymentAcquirer, self).create(vals)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/odoo/models.py", line 3516, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/odoo/models.py", line 3602, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/opt/odoo/odoo/odoo/fields.py", line 1934, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1946, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for payment.acquirer.provider: 'mollie'

**Comment by HafedhRahmani** [comment]
@ipsecurity 
Thank you for your comment,
The module installs correctly for both odoo 12 enterprise and community version.
So that we can reproduce the problem know you tell us:
Which version do you use? Release of which date stp?
Your database is demo?
Thank you!

**Comment by ipsecurity** [comment]
Hi,

We use v12 enterprise and the latest download of odoo mollie plugin. Our database is an production database

[cid:image001.png@01D4D36F.395DB4A0]

Kind Regards/ Met vriendelijke groet,

Maarten Goedhart



Van: HafedhRahmani <notifications@github.com>
Verzonden: dinsdag 5 maart 2019 15:12
Aan: mollie/mollie-odoo <mollie-odoo@noreply.github.com>
CC: Maarten Goedhart | IP-SecurITy <maarten@ip-security.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mollie/mollie-odoo] Migration to Odoo 12.0 (#13)


@ipsecurity<https://github.com/ipsecurity>
Thank you for your comment,
The module installs correctly for both odoo 12 enterprise and community version.
So that we can reproduce the problem know you tell us:
Which version do you use? Release of which date stp?
Your database is demo?
Thank you!

**Comment by HafedhRahmani** [comment]
Hi,
Do you use mollie module from branch 12.0? or master ?!
you must use 12.0.

**Comment by ipsecurity** [comment]
Hi the one downloaded from odoo app repository for 12.0

Met vriendelijke groet,

Maarten Goedhart


Op 5 mrt. 2019 om 16:26 heeft HafedhRahmani <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi,
Do you use mollie module from branch 12.0? or master ?!
you must use 12.0.

**Comment by Yenthe666** [comment]
@gclauwae the doc page (https://github.com/mollie/mollie-odoo/tree/12.0) mentions `pip install mollie-api-python==1.2.0` but this should be `pip3`, right? I took a look at the dependency on both P2 and P3 but this seems to give issues on Ubuntu 18.04 with this package version. Result:
![image](https://user-images.githubusercontent.com/6352350/54145881-210a8500-442f-11e9-9437-588475805880.png)
I just did a check like in the controller:
https://github.com/mollie/mollie-odoo/blob/e339e61c77b67efeaba6897834bd84bd240155e3/payment_mollie_official/controllers/main.py#L24
It works fine with Python 3 & version `2.1.0` from the `mollie-api-python` package. I've submitted a PR for the package handling in a `requirements.txt` file already at https://github.com/mollie/mollie-odoo/pull/15

After the dependency issues - or just a lack of knowledge/insight - everything works just fine out of the box:
![image](https://user-images.githubusercontent.com/6352350/54146276-e8b77680-442f-11e9-9853-0018d77d40c7.png)

I can verify it installs fine out of the box on V12.

**Comment by ipsecurity** [comment]
Thnx!  This solved the installation issue

Met vriendelijke groet,

Maarten Goedhart


Op 11 mrt. 2019 om 19:00 heeft Yenthe V.G <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@gclauwae<https://github.com/gclauwae> the doc page (https://github.com/mollie/mollie-odoo/tree/12.0) mentions pip install mollie-api-python==1.2.0 but this should be pip3, right? I took a look at the dependency on both P2 and P3 but this seems to give issues on Ubuntu 18.04 with this package version. Result:
[image]<https://user-images.githubusercontent.com/6352350/54145881-210a8500-442f-11e9-9437-588475805880.png>
I just did a check like in the controller:
https://github.com/mollie/mollie-odoo/blob/e339e61c77b67efeaba6897834bd84bd240155e3/payment_mollie_official/controllers/main.py#L24
It works fine with Python 3 & version 2.1.0 from the mollie-api-python package. I've submitted a PR for the package handling in a requirements.txt file already at #15<https://github.com/mollie/mollie-odoo/pull/15>

After the dependency issues - or just not enough information - everything works just fine out of the box:
[image]<https://user-images.githubusercontent.com/6352350/54146276-e8b77680-442f-11e9-9853-0018d77d40c7.png>

**Comment by mgielissen** [comment]
When doing a payment, the reference in Mollie shows 'Order ODOO538' instead of Odoo ordername 'SO2019-536'

**Comment by mgielissen** [comment]
When the customer zipcode is not filled in, or the phone iss not in E.164 format, the Mollie payment screen is not shown to the customer.  Mollie gives a error in the Odoo logfile.

2019-03-18 20:58:42,599 1 INFO db werkzeug: 172.17.0.2 - - [18/Mar/2019 20:58:42] "POST /shop/payment/transaction/ HTTP/1.1" 200 - 52 0.031 0.039
2019-03-18 20:58:42,732 1 INFO db odoo.addons.payment_mollie_official.models.sale_order: ERROR! The 'phone' field should contain a valid phone number, in E.164 format
2019-03-18 20:58:42,737 1 INFO db werkzeug: 172.17.0.2 - - [18/Mar/2019 20:58:42] "POST /payment/mollie/intermediate HTTP/1.1" 302 - 24 0.012 0.052

**Comment by Yenthe666** [comment]
@mgielissen all the issues you mention should be fixed now and the module is migrated to V12. Any chance you can close this one?
