### ISSUE TITLE
[12.0] 500: Internal Server Error when clicking on an unpaid invoice under My Account

### ISSUE THREAD

**Issue by mgielissen** [mollie/mollie-odoo#17]
Steps to reproduce:

1. Invoice Online Payment = enabled
2. Goto My Account (/my/home)
3. Click on Invoices (/my/invoices)
4. Click on a unpaid Invoice:

 **Error message:**

'NoneType' object has no attribute 'get_available_methods'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_payment_mollie_official_mollie_payment_gateway_list_4746
AttributeError: 'NoneType' object has no attribute 'get_available_methods'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'get_available_methods'
Template: payment_mollie_official.mollie_payment_gateway_list
Path: /templates/t/t[1]
Node: <t t-set="gateways" t-value="website_sale_order.get_available_methods(mollie_aq.payment_icon_ids)"/>
        

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_payment_mollie_official_mollie_payment_gateway_list_4746
AttributeError: 'NoneType' object has no attribute 'get_available_methods'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 833, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 340, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1268, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1261, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1282, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 303, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1291, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1098_4714
  File "<template>", line 2, in body_call_content_4713
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_payment_portal_invoice_payment_4723
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_payment_payment_tokens_list_4740
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 351, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'NoneType' object has no attribute 'get_available_methods'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_payment_mollie_official_mollie_payment_gateway_list_4746
AttributeError: 'NoneType' object has no attribute 'get_available_methods'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'get_available_methods'
Template: payment_mollie_official.mollie_payment_gateway_list
Path: /templates/t/t[1]
Node: <t t-set="gateways" t-value="website_sale_order.get_available_methods(mollie_aq.payment_icon_ids)"/>

**Comment by gclauwae** [comment]
Thx, for mentioning this, we indeed did not tested this scenario. We keep you posted.

**Comment by gclauwae** [comment]
Error Fixed, however online payment for an invoice is not yet possible, only wire transfer will be visible.

**Comment by Yenthe666** [comment]
Reproduced very similar behaviour in the frontend part with the Mollie app on the following line:
https://github.com/mollie/mollie-odoo/blob/009adff2466ea7b690256520598229ded49bb5f4/payment_mollie_official/views/payment_templates.xml#L19

Traceback:
```
Error to render compiling AST
AttributeError: 'int' object has no attribute 'payment_icon_ids'
Template: payment_mollie_official.mollie_payment_gateway_list
Path: /templates/t/t[1]
Node: <t t-set="gateways" t-value="website_sale_order.get_available_methods(mollie_aq.payment_icon_ids)"/>
```

Coming back from:
https://github.com/mollie/mollie-odoo/blob/009adff2466ea7b690256520598229ded49bb5f4/payment_mollie_official/views/payment_templates.xml#L104
and
https://github.com/mollie/mollie-odoo/blob/009adff2466ea7b690256520598229ded49bb5f4/payment_mollie_official/views/payment_templates.xml#L43
Which does not evaluate as "0", this comparision is invalid

Coming back from:
https://github.com/mollie/mollie-odoo/blob/009adff2466ea7b690256520598229ded49bb5f4/payment_mollie_official/views/payment_templates.xml#L46
Which is not set if the payment method 'Mollie' is not activated.
As Odoo tries to get data from the Mollie payment method but there is none the XML template will fail if the payment method Mollie is not activated.
Fix provided at https://github.com/mollie/mollie-odoo/pull/26

**Comment by Yenthe666** [comment]
Fixed at https://github.com/mollie/mollie-odoo/commit/5fb6505f96860796c15c239f03d11d984068d52f - it should also solve your issue :)
