### ISSUE TITLE
Installation fails "cannot find parent view"

### ISSUE THREAD

**Issue by Peltier1977** [mollie/mollie-odoo#38]
Hi,

while searching for payment options for our odoo shop i found this plugin.
but installation fails at my machine, please help.
for me it looks like i´m missing some preconditions?
Or maybe somthing with my German odoo installation?

The error:
**Element '<xpath expr="//group[@name='sale_info']">' kann nicht in der übergeordneten Ansicht lokalisiert werden.**
means somthing like "cannot find parent view"

My Setup: Window 10, Odoo 12

i will explain what i did and paste the message:

1) i installed the python libs when executing those lines again i get for example:
Requirement already satisfied: mollie-api-python==2.1.0 in c:\program files (x86)\odoo 12.0\python\lib\site-packages (2.1.0)
2) i restarted odoo several times

3) the error at the odoo app installer is:
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1108, in _validate_fields
    check(self)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 794, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 742, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 720, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//group[@name='sale_info']">' kann nicht in der übergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `mollie.view.order.form.inherit`
[view_id: 1943, xml_id: k. A., model: sale.order, parent_id: 1280]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3868, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\website\models\ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3782, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3599, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1125, in determine_inverse
    getattr(records, self.inverse)()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\website\models\ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3324, in write
    self._write(store_vals)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3460, in _write
    self._validate_fields(vals)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Fehler während der Constraint-Validierung\n\nElement \'<xpath expr="//group[@name=\'sale_info\']">\' kann nicht in der übergeordneten Ansicht lokalisiert werden.\n\nFehler Kontext:\nAnsicht `mollie.view.order.form.inherit`\n[view_id: 1943, xml_id: k. A., model: sale.order, parent_id: 1280]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 764, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3868, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\website\models\ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3782, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3599, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1125, in determine_inverse
    getattr(records, self.inverse)()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\website\models\ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\base\models\ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3324, in write
    self._write(store_vals)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3460, in _write
    self._validate_fields(vals)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Fehler während der Constraint-Validierung

Element '<xpath expr="//group[@name='sale_info']">' kann nicht in der übergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `mollie.view.order.form.inherit`
[view_id: 1943, xml_id: k. A., model: sale.order, parent_id: 1280]
None" while parsing file:/c:/program%20files%20(x86)/odoo%2012.0/server/custom_addons/payment_mollie_official/views/sale_order.xml:3, near
<record model="ir.ui.view" id="mollie_view_order_form_inherit">
        <field name="name">mollie.view.order.form.inherit</field>
        <field name="model">sale.order</field>
        <field name="inherit_id" ref="sale.view_order_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//group[@name='sale_info']" position="after">
                <group string="Mollie connection">
                    <div class="three-inline-buttons">
                        <strong>Mollie ref.</strong>
                        <t t-if="record.acquirer_reference">
	                        <button name="action_go_to_mollie_order" type="object" class="oe_link mollie_link">
                                <field name="acquirer_reference" readonly="1"/>
                            </button>
                        </t>
                        <button name="%(force_update_field_view_action)d" string="_Set a Mollie reference" class="oe_link mollie_link" context="{'default_acquirer_reference':acquirer_reference}" groups="base.group_no_one" type="action"/>
                    </div>
                    <field name="acquirer_method"/>
                </group>
            </xpath>
            <xpath expr="//page[@name='order_lines']//field[@name='state']" position="after">
                <group string="Mollie connection">
                    <div>
                        <label for="acquirer_reference"/>
                        <field name="acquirer_reference" readonly="1"/>
                        <button name="%(force_update_field_view_action)d" string="_Update" class="oe_link" context="{'default_acquirer_reference':acquirer_reference}" groups="base.group_no_one" type="action"/>
                    </div>
                </group>
            </xpath>
        </data></field>
    </record>
```

**Comment by Yenthe666** [comment]
@Peltier1977 it cannot find the group `sale_info` in the sales view. Could it be that you have custom development or a third party app that has removed this tab, renamed it or moved it elsewhere?

**Comment by Peltier1977** [comment]
Thanks for your time, i found the solution. i was using the master instead of the 12.0 branch, where this xpath element is named _sale_pay_.

it works now!

**Comment by Yenthe666** [comment]
Ahh.. I've asked the maintainers of this repository to set the default branch to a major version before but they haven't done it yet sadly.
