### ISSUE TITLE
v13 issue installing mollie app

### ISSUE THREAD

**Issue by odoo-mvds** [mollie/mollie-odoo#58]
Beste

bij het proberen te installeren van de app vanaf jullie code. Krijgen we de volgende error:

Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('payment.acquirer(13,).module_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-66>", line 2, in button_immediate_upgrade
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 634, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 571, in _button_immediate_function
    self._cr.commit()
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 389, in commit
    flush_env(self)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 68, in flush_env
    env['base'].flush()
  File "/home/odoo/src/odoo/odoo/models.py", line 5389, in flush
    self.recompute()
  File "/home/odoo/src/odoo/odoo/models.py", line 5799, in recompute
    process(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 5783, in process
    recs.mapped(field.name)
  File "/home/odoo/src/odoo/odoo/models.py", line 5206, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/src/odoo/odoo/models.py", line 5165, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/src/odoo/odoo/models.py", line 5165, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/src/odoo/odoo/models.py", line 5610, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 991, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1105, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 3915, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/addons/payment/models/payment_acquirer.py", line 200, in _compute_color
    if acquirer.module_id and not acquirer.module_state == 'installed':
  File "/home/odoo/src/odoo/odoo/fields.py", line 2255, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1003, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 2944, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/odoo/models.py", line 3016, in _read
    cr.execute(query_str, params)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 164, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 241, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column payment_acquirer.create_shipment_notification does not exist
LINE 1: ...r"."mollie_api_key_prod" as "mollie_api_key_prod","payment_a...
                                                             ^

Wat moeten we doen? Onze DB draait op odoo.sh

bedankt,

**Comment by ploegvde** [comment]
Als het goed is heb je de mollie repo als submodule toegevoegd aan je eigen repository. Welke versie gebruik je? Heb je de just versie van de module?

**Comment by odoo-mvds** [comment]
zie screenshot. geen submodule gebruikt. Gewoon de code gedownload en deze via een nieuwe branch geupload op odoo.sh.

![image](https://user-images.githubusercontent.com/59664044/78585716-9e731580-783a-11ea-9c65-3739b36e45b7.png)

**Comment by ghost** [comment]
@odoo-mvds Hello
You need to do the restart the environment properly and then update the module "payment_mollie_official" again.
It will be working if the module "payment_mollie_official" will be properly updated in the environment.

Thank you.

**Comment by odoo-mvds** [comment]
Hello,

Ok, in dev it worked.

The source eventually was that we needed to install your module before
merging the bug 56 code... Uninstalling it from our DB and starting from
scratch solved it.

The ticket can be closed.

br,
Met vriendelijke groeten,
<https://www.facebook.com/vdsitsolutions> <http://www.vdsit.be/>
Michael Vandesompel
Zaakvoerder
24/7 SUPPORT:
+32 59 795 111
E‑MAIL SUPPORT:
mv@vdsit.be


Op di 7 apr. 2020 om 15:47 schreef Odoo Experts B.V. <
notifications@github.com>:
