### ISSUE TITLE
warnings  on install 12 (odoo.sh / enterprise

### ISSUE THREAD

**Issue by Agacolor** [mollie/mollie-odoo#78]
note: Installing the module (12) throws a warning and orange status indicator on branch

WARNING (..) odoo.models: The model force.update.data has no _description
WARNING (..) odoo.models: ir.cron.create() with unknown fields: function
WARNING (..) odoo.models: ir.actions.todo.create() with unknown fields: type
WARNING (..) odoo.modules.loading: The transient model config.mollie (Set up config mollie) should not have explicit access rules!

**Comment by ghost** [comment]
@Agacolor Hello
Thanks for the indication. We have solved the warnings.
You can check here https://github.com/mollie/mollie-odoo/pull/82

**Comment by Agacolor** [comment]
Thank you very much for the update.
I think in payment_mollie_official/data/ir_cron.xml the line  <field name="code">>model.clean_old_logging()</field> contains one ">" too many ?

**Comment by odoo-mvds** [comment]
A new version was released a few days ago. We strongly advice to upgrading the module. Please do this first in a staging server to see if the upgrade is working fine in your DB.

**Comment by Agacolor** [comment]
Hi there,

1) I tried installing the newest release for version 12.  I got several errors when installing in the staging server (red traffic light)
[odoo 12 enterprise on Odoo.sh] see errors below. Conflict with other modules ?

2) The instance in development builds without errors (only base + mollie installed) so conflict with other modules?

3) When I install from Odoo.sh directly (deploy option) the build fails with 
odoo.exceptions.UserError: ('Unable to install module "payment_mollie_official" because an external dependency is not met: No module named mollie', '')

ad 1)
Errors below. 

Front end error pop up:

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /payment_mollie_official/static/src/css/payment_mollie_official.css defined in bundle 'web.assets_frontend'.

Odoo Server Error (log fle)

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1131, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Field `dashboard_url` does not exist

Error context:
View `payment.acquirer.form.inherit.2`
[view_id: 8689, xml_id: n/a, model: payment.acquirer, parent_id: 1311]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 3893, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 3807, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3624, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1148, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3349, in write
    self._write(store_vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3485, in _write
    self._validate_fields(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `dashboard_url` does not exist\n\nError context:\nView `payment.acquirer.form.inherit.2`\n[view_id: 8689, xml_id: n/a, model: payment.acquirer, parent_id: 1311]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 3893, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 3807, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3624, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1148, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3349, in write
    self._write(store_vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3485, in _write
    self._validate_fields(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `dashboard_url` does not exist

Error context:
View `payment.acquirer.form.inherit.2`
[view_id: 8689, xml_id: n/a, model: payment.acquirer, parent_id: 1311]
None" while parsing /home/odoo/src/user/mollie-odoo-12.0/payment_mollie_official/views/payment_views.xml:3, near
<record id="acquirer_form_view_mollie_222" model="ir.ui.view">
        <field name="name">payment.acquirer.form.inherit.2</field>
        <field name="model">payment.acquirer</field>
        <field name="inherit_id" ref="payment.acquirer_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//group[@name=&quot;acquirer&quot;]" position="inside">
                <group attrs="{'invisible': [('provider', '!=', 'mollie')]}">
                    <field name="mollie_api_key_test" attrs="{'required':[ ('provider', '=', 'mollie'), ('environment', '=', 'test')]}" password="True"/>
                    <field name="mollie_api_key_prod" attrs="{'required':[ ('provider', '=', 'mollie'), ('environment', '=', 'enabled')]}" password="True"/>
                    <field name="mollie_profile_id" attrs="{'required':[ ('provider', '=', 'mollie'), ('environment', '=', 'enabled')]}" password="True"/>
                </group>
            </xpath>
            <page name="acquirer_credentials" position="after">
                <page string="Mollie Payment Methods" attrs="{'invisible': [('provider', '!=', 'mollie')]}">
                    <field name="mollie_methods_ids">
                        <tree create="0" editable="bottom">
                            <field name="sequence" widget="handle"/>
                            <field name="name"/>
                            <field name="method_id_code"/>
                            <field name="payment_icon_ids" widget="many2many_tags"/>
                            <field name="active" invisible="1"/>
                            <field name="journal_id"/>
                            <field name="active_on_shop" widget="boolean_toggle"/>
                            <field name="min_amount" invisible="1"/>
                            <field name="min_amount" invisible="1"/>
                            <field name="supports_order_api" invisible="1"/>
                            <field name="supports_payment_api" invisible="1"/>
                            <field name="payment_issuer_ids" widget="many2many_tags" invisible="1"/>
                        </tree>
                    </field>
                    <button type="object" name="action_mollie_sync_methods" class="btn btn-link">
                        <span><i class="fa fa-refresh"/> Sync payment methods </span>
                    </button>
                </page>
            </page>
        </data></field>
    </record>

**Comment by odoo-mvds** [comment]
Hello,

you are missing the mollie dependancies. You can find these in the requirement.txt file.

br,

**Comment by Agacolor** [comment]
Hello odoo-mvds. Still experiencing some issues. Perhaps easier to discuss viva voce. 
(ibaas@agacolor.com)
